version: '3.8'

services:
  # Aplicacion PHP
  app:
    build: .
    ports:
      - "8087:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    networks:
      - weather_network

  # Base de datos MariaDB
  db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: weather_db
      MYSQL_USER: weather_user
      MYSQL_PASSWORD: weather_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - weather_network

volumes:
  db_data:

networks:
  weather_network:
